
#
#   make - configuration
#

    SRM_NAME=srm-panorama-hdrpanorama

#
#   make - synchronize
#

    all:directories
	cp src/$(SRM_NAME) bin/$(SRM_NAME)

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
