#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

# SRM standard variables #
SRM_MPOINT="/data/"

# Argument and parameter parser
#
# This function simply reads the arguments and parameter and stores the
# parameters in the configured variables.

function srm_arg() {

    # Parses the arguments and parameters #
    while [[ $# > 0 ]]; do

        # Push token and update cursor #
        srm_push="$1"; shift

        # Switch on arguments #
        case $srm_push in

            --mount-point)
                SRM_MPOINT="$1"; shift

        esac

    done

}

# Message display
#
# This function simply display the string provdided as parameter on the standard
# error output.

function srm_echo() {

    # Display message on standard error output #
    >&2 echo $1
    
}

