#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

    # Storage variables #
    SRM_MNT_BASE="/data/"

    # Execution variables #
    SRM_KER_FORC="false"
    SRM_KER_MODE="unknown"

    # Temporary storage variables #
    SRM_TMP_NAME=""

    # Communication variables #
    SRM_IO_PATH=""
    SRM_IO_IPOS=""
    SRM_IO_OPOS=""

    # Parallel variables #
    SRM_PLL_CONF="1"

    # Signal variables #
    SRM_SIG_EXIT=0

# Argument and parameter
#
# This function reads the module script arguments and parameters using the
# assuption that every argument always comes with a unique parameter.

    function srm_arg() {

        # Arguments and parameters #
        while [[ $# > 0 ]]; do

            # Read token and update head #
            srm_arg="$1"; shift
            srm_prm="$1"; shift

            # Switch on arguments #
            case $srm_arg in

                --mount-point)
                    SRM_MNT_BASE="$srm_prm"
                ;;
                --local-thread)
                    SRM_PLL_CONF="$srm_prm"
                ;;
                --force)
                    SRM_KER_FORC="$srm_prm"
                ;;
                --io)
                    SRM_IO_PATH="$srm_prm"
                ;;

            esac

        done

    }

# Message display
#
# The following function simply displays the string provdided as parameter using
# the standard error output.

    function srm_echo() {

        # Display message #
        >&2 echo "$1"
        
    }

# Timestamps hashing
#
# This function returns the hashed (truncated) timestamps value for any given
# timestamp according to the storage structure standards. It corresponds to a
# simple division by ten.

    function srm_tshash() {

        # Retrieve unix timestamps #
        SRM_TS_UNIX=(${1//_/ })

        # Returns hashed timestmap #
        echo $(( ${SRM_TS_UNIX[0]} / 100 ))

    }

# Temporary file system
#
# This function creates a temporary storage (tmpfs) in case module requires
# fast-access storage. It also allows to delete the temporary storage as the
# module ends its task.

    function srm_tmpfs() {

        # Create temporary storage path #
        SRM_TMP_NAME=/run/shm/$(echo "$SRM_IO_PATH" | sha256sum | cut -c 1-32)

        # Temporary storage management #
        if [ "$1" == "create" ]; then

            # Create temporary storage #
            mkdir -p $SRM_TMP_NAME

        elif [ "$1" == "delete" ]; then

            # Check temporary storage #
            if [ -d $SRM_TMP_NAME ]; then

                # Delete temporary storage #
                rm -rf $SRM_TMP_NAME

            fi

        fi

    }

# Calibration data access
#
# This function allows to query calibration data through the standard storage
# structure. It expects the device MAC address and the key of the desired value
# and returns it when the key is found in the calibration data. An empty string
# is return otherwise.

    function srm_askc() {

        # Read and returns value of key #
        echo $(grep "$2" $SRM_MNT_BASE/camera/$1/fastcal/calibration.key | cut -d'=' -f2)

    }

# Module kernel specific function (norama@eyesis4pi)
#
#

    function srm_norama_eyesis4pi() {

        # Parsing source files #
        for SRM_TILE in $(seq -f '%02g' 0 $(( $(srm_askc $1 "channels") - 1 ))); do

            # Retrieve projection angles #
            SRM_AZIM=$(srm_askc $1 "azimuth_$SRM_TILE"  ); SRM_AZIM=${SRM_AZIM//+}; SRM_AZIM=$(echo "(${SRM_AZIM/[eE]/*10^})*(180/3.1415926535)" | bc -l)
            SRM_HEAD=$(srm_askc $1 "heading_$SRM_TILE"  ); SRM_HEAD=${SRM_HEAD//+}; SRM_HEAD=$(echo "(${SRM_HEAD/[eE]/*10^})*(180/3.1415926535)" | bc -l)
            SRM_ELEV=$(srm_askc $1 "elevation_$SRM_TILE"); SRM_ELEV=${SRM_ELEV//+}; SRM_ELEV=$(echo "(${SRM_ELEV/[eE]/*10^})*(180/3.1415926535)" | bc -l)
            SRM_ROLL=$(srm_askc $1 "roll_$SRM_TILE"     ); SRM_ROLL=${SRM_ROLL//+}; SRM_ROLL=$(echo "(${SRM_ROLL/[eE]/*10^})*(180/3.1415926535)" | bc -l)

            # Compute inverted gnomonic projection #
            norama-invert -E -i $SRM_IO_IPOS/${SRM_IO_POSE}_$SRM_TILE.tiff -o $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff \
            --interpolation bicubicf \
            --threads    1 \
            --eqr-width  $(srm_askc $1 "equirectangularWidth_$SRM_TILE") \
            --eqr-height $(srm_askc $1 "equirectangularHeight_$SRM_TILE") \
            --map-width  $(srm_askc $1 "ImageFullWidth_$SRM_TILE") \
            --map-height $(srm_askc $1 "ImageFullLength_$SRM_TILE") \
            --sight-x    $(srm_askc $1 "px0_$SRM_TILE") \
            --sight-y    $(srm_askc $1 "py0_$SRM_TILE") \
            --tile-x     $(srm_askc $1 "XPosition_$SRM_TILE") \
            --tile-y     $(srm_askc $1 "YPosition_$SRM_TILE") \
            --azimuth    $SRM_AZIM \
            --heading    $SRM_HEAD \
            --elevation  $SRM_ELEV \
            --roll       $SRM_ROLL \
            --focal      $(srm_askc $1 "focalLength_$SRM_TILE") \
            --pixel      $(srm_askc $1 "pixelSize_$SRM_TILE")

            # Insert alpha channel #
            convert $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff $SRM_MNT_BASE/camera/$1/calibration/masks/mask-$SRM_TILE.tiff -compose copyopacity -composite $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff

            tiffset -s 286 $(srm_askc $1 "XPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff
            tiffset -s 287 $(srm_askc $1 "YPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff

            # Inject result in storage structure #
            rsync $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff $SRM_IO_OPOS/${SRM_IO_POSE}_$SRM_TILE.tiff

            # Specific channel splitting #
            if [ "$SRM_TILE" = "04" ] || [ "$SRM_TILE" == "12" ] || [ "$SRM_TILE" == "22" ]; then

                # Retrieve panoramic and tile width #
                SRM_PWIDTH=$(srm_askc $1 "ImageFullWidth_$SRM_TILE")
                SRM_TWIDTH=$(srm_askc $1 "equirectangularWidth_$SRM_TILE")

                # Compute split point #
                SRM_SPLITX=$(( $SRM_PWIDTH - $SRM_TWIDTH ))

                # Compute remaining width #
                SRM_RWIDTH=$(( $SRM_TWIDTH - $SRM_SPLITX ))

                convert $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff -crop ${SRM_SPLITX}x$(srm_askc $1 "equirectangularHeight_$SRM_TILE")+0+0 $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_L.tiff
                convert $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE.tiff -crop ${SRM_RWIDTH}x$(srm_askc $1 "equirectangularHeight_$SRM_TILE")+$(($SRM_SPLITX+1))+0 $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_R.tiff

                tiffset -s 286 $(srm_askc $1 "XPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_L.tiff
                tiffset -s 287 $(srm_askc $1 "YPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_L.tiff

                tiffset -s 286 $(srm_askc $1 "XPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_R.tiff
                tiffset -s 287 $(srm_askc $1 "YPosition_$SRM_TILE") $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_R.tiff

                # Inject results in storage structure #
                rsynch $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_L.tiff $SRM_IO_OPOS/${SRM_IO_POSE}_$SRM_TILE_L.tiff
                rsynch $SRM_TMP_NAME/${SRM_IO_POSE}_$SRM_TILE_R.tiff $SRM_IO_OPOS/${SRM_IO_POSE}_$SRM_TILE_R.tiff

            fi

        done

    }

# Module kernel function
#
# The following instructions are responsible of performing the tasks the module
# is supposed to do and constitute the main kernel function. The kernel function
# is broadcasted to the different available computers according to the specified
# network topology.

    # Arguments and parameters #
    srm_arg $@

    # Decompose IO buffer #
    SRM_IO_PART=(${SRM_IO_PATH//,/ })

    # Compose pose identification #
    SRM_IO_POSE=${SRM_IO_PART[5]}

    # Compose source and destination #
    SRM_IO_IPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[0]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}
    SRM_IO_OPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[1]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}

    # Check source element #
    if [ ! -d $SRM_IO_IPOS ]; then

        # Display message #
        srm_echo "SRM Kernel : Error, invalid module kernel io specification"

        # Update exit code #
        SRM_SIG_EXIT=1

    else

        # Check device #
        if [[ ! $(cat $SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/fastcal/calibration.key | grep "type=") == *"=eyesis4pi" ]]; then

            # Display message #
            srm_echo "SRM Kernel : Error, unknown device type"

            # Update exit code #
            SRM_SIG_EXIT=1

        else

            # Display message #
            srm_echo "    pose ${SRM_IO_PART[5]} of camera ${SRM_IO_PART[2]}"

            # Temporary storage #
            srm_tmpfs create

            # Check pose #
            if ( [ -d $SRM_IO_OPOS ] && [ "$SRM_KER_FORC" == "true" ] ) || [ ! -d $SRM_IO_OPOS ]; then

                # Remove previous data #
                if [ -d $SRM_IO_OPOS ]; then rm -rf $SRM_IO_OPOS; fi

                # Create destination directory #
                mkdir -p $SRM_IO_OPOS

                # Refinement process #
                srm_norama_eyesis4pi ${SRM_IO_PART[2]}

            fi

            # Temporary storage #
            srm_tmpfs delete

        fi

    fi

    # Exit code #
    exit $SRM_SIG_EXIT

