#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

    # Storage variables #
    SRM_MNT_BASE="/data/"

    # Execution variables #
    SRM_KER_FORC="false"

    # Temporary storage variables #
    SRM_TMP_NAME=""

    # Communication variables #
    SRM_IO_PATH=""
    SRM_IO_IPOS=""
    SRM_IO_OPOS=""

    # Parallel variables #
    SRM_PLL_CONF="1"

    # Signal variables #
    SRM_SIG_EXIT=0

# Argument and parameter
#
# This function reads the module script arguments and parameters using the
# assuption that every argument always comes with a unique parameter.

    function srm_arg() {

        # Arguments and parameters #
        while [[ $# > 0 ]]; do

            # Read token and update head #
            srm_arg="$1"; shift
            srm_prm="$1"; shift

            # Switch on arguments #
            case $srm_arg in

                --mount-point)
                    SRM_MNT_BASE="$srm_prm"
                ;;
                --local-thread)
                    SRM_PLL_CONF="$srm_prm"
                ;;
                --force)
                    SRM_KER_FORC="$srm_prm"
                ;;
                --io)
                    SRM_IO_PATH="$srm_prm"
                ;;
                -m)
                    SRM_KER_MODE="$srm_prm"
                ;;

            esac

        done

    }

# Message display
#
# The following function simply displays the string provdided as parameter using
# the standard error output.

    function srm_echo() {

        # Display message #
        >&2 echo "$1"
        
    }

# Timestamps hashing
#
# This function returns the hashed (truncated) timestamps value for any given
# timestamp according to the storage structure standards. It corresponds to a
# simple division by ten.

    function srm_tshash() {

        # Retrieve unix timestamps #
        SRM_TS_UNIX=(${1//_/ })

        # Returns hashed timestmap #
        echo $(( ${SRM_TS_UNIX[0]} / 100 ))

    }

# Temporary file system
#
# This function creates a temporary storage (tmpfs) in case module requires
# fast-access storage. It also allows to delete the temporary storage as the
# module ends its task.

    function srm_tmpfs() {

        # Create temporary storage path #
        SRM_TMP_NAME=/run/shm/$(echo "$SRM_IO_PATH" | sha256sum | cut -c 1-32)

        # Temporary storage management #
        if [ "$1" == "create" ]; then

            # Create temporary storage #
            mkdir -p $SRM_TMP_NAME

        elif [ "$1" == "delete" ]; then

            # Check temporary storage #
            if [ -d $SRM_TMP_NAME ]; then

                # Delete temporary storage #
                rm -rf $SRM_TMP_NAME

            fi

        fi

    }

# Module kernel specific function - Enblend@Eyesis4pi
#
# 

    function srm_enblend_eysis4pi() {

        # Extract timestamps #
        SRM_EXE_TIME=$(basename $1); 
        SRM_EXE_TIME=(${SRM_EXE_TIME//_/ })

        # Stitching of upper band #
        enblend -w -o $SRM_TMP_NAME/tmp_top_band.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_04_R.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_05.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_06.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_07.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_00.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_01.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_02.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_03.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_04_L.tiff &> /dev/null

        # Stitching of middle band #
        enblend -w -o $SRM_TMP_NAME/tmp_mid_band.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_12_R.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_13.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_14.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_15.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_08.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_09.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_10.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_11.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_12_L.tiff &> /dev/null

        # Stitching of bottom band #
        enblend -w -o $SRM_TMP_NAME/tmp_bot_band.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_20_R.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_21.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_22.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_23.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_16.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_17.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_18.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_19.tiff \
        $1/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}_20_L.tiff &> /dev/null

        # Stitching horizontal bands #
        enblend --wrap='vertical' -o $2/${SRM_EXE_TIME[0]}_${SRM_EXE_TIME[1]}.tiff \
        $SRM_TMP_NAME/tmp_top_band.tiff \
        $SRM_TMP_NAME/tmp_mid_band.tiff \
        $SRM_TMP_NAME/tmp_bot_band.tiff &> /dev/null

    }

# Module kernel function
#
# The following instructions are responsible of performing the tasks the module
# is supposed to do and constitute the main kernel function. The kernel function
# is broadcasted to the different processing computer according to the available
# network topology.

    # Arguments and parameters #
    srm_arg $@

    # Decompose IO buffer #
    SRM_IO_PART=(${SRM_IO_PATH//,/ })

    # Compose source and destination #
    SRM_IO_IPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[0]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}
    SRM_IO_OPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[1]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}

    # Check source element #
    if [ ! -d $SRM_IO_IPOS ]; then

        # Display message #
        srm_echo "SRM Kernel : Error, invalid module kernel io specification"

        # Update exit code #
        SRM_SIG_EXIT=1

    else

        # Display message #
        srm_echo "    pose ${SRM_IO_PART[5]} of camera ${SRM_IO_PART[2]}"

        # Temporary storage #
        srm_tmpfs create

        # Check pose #
        if ( [ -d $SRM_IO_OPOS ] && [ "$SRM_KER_FORC" == "true" ] ) || [ ! -d $SRM_IO_OPOS ]; then

            # Check stitching method #
            if [ "$SRM_KER_MODE" == "enblend" ]; then

                # Check camere device #
                if [[ $(cat $SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/fastcal/calibration.key | grep "type=") == *"=eyesis4pi"* ]]; then

                    # Check destination pose directory #
                    if [ -d $SRM_IO_OPOS ]; then

                        # Remove previous processed data #
                        rm -rf $SRM_IO_OPOS

                    fi

                    # Create destination pose directory #
                    mkdir -p $SRM_IO_OPOS

                    # Refinement process #
                    srm_enblend_eysis4pi $SRM_IO_IPOS $SRM_IO_OPOS

                else

                    # Display message #
                    srm_echo "SRM Kernel : Error, unknwon type of device"

                    # Update exit code #
                    SRM_SIG_EXIT=1

                fi

            else

                # Display message #
                srm_echo "SRM Kernel : Error, invalid module kernel mode specification"

                # Update exit code #
                SRM_SIG_EXIT=1

            fi

        fi

        # Temporary storage #
        srm_tmpfs delete

    fi

    # Exit code #
    exit $SRM_SIG_EXIT

