
#
#   make - configuration
#

    SRM_NAME=srm-template

#
#   make - synchronize
#

    all:directories

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
