#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

    # Storage variables #
    SRM_MNT_BASE="/data/"

    # Execution variables #
    SRM_KER_FORC="false"
    SRM_KER_MODE="unknown"

    # Temporary storage variables #
    SRM_TMP_NAME=""

    # Communication variables #
    SRM_IO_PATH=""
    SRM_IO_IPOS=""
    SRM_IO_OPOS=""

    # Parallel variables #
    SRM_PLL_CONF="1"

    # Signal variables #
    SRM_SIG_EXIT=0

# Argument and parameter
#
# This function reads the module script arguments and parameters using the
# assuption that every argument always comes with a unique parameter.

    function srm_arg() {

        # Arguments and parameters #
        while [[ $# > 0 ]]; do

            # Read token and update head #
            srm_arg="$1"; shift
            srm_prm="$1"; shift

            # Switch on arguments #
            case $srm_arg in

                --mount-point)
                    SRM_MNT_BASE="$srm_prm"
                ;;
                --local-thread)
                    SRM_PLL_CONF="$srm_prm"
                ;;
                --force)
                    SRM_KER_FORC="$srm_prm"
                ;;
                --io)
                    SRM_IO_PATH="$srm_prm"
                ;;
                -m)
                    SRM_KER_MODE="$srm_prm"
                ;;

            esac

        done

    }

# Message display
#
# The following function simply displays the string provdided as parameter using
# the standard error as output.

    function srm_echo() {

        # Display message #
        >&2 echo "$1"
        
    }

# Timestamps hashing
#
# This function returns the hashed (truncated) timestamps value for any given
# timestamp according to the storage structure standards. It corresponds to a
# simple division by ten.

    function srm_tshash() {

        # Retrieve unix timestamps #
        SRM_TS_UNIX=(${1//_/ })

        # Returns hashed timestamps #
        echo $(( ${SRM_TS_UNIX[0]} / 100 ))

    }

# Temporary file system
#
# This function creates a temporary storage (tmpfs) in case module requires
# fast-access storage. It also allows to delete the temporary storage as the
# module ends its task.

    function srm_tmpfs() {

        # Create temporary storage path #
        SRM_TMP_NAME=/run/shm/$(echo "$SRM_IO_PATH" | sha256sum | cut -c 1-32)

        # Temporary storage management #
        if [ "$1" == "create" ]; then

            # Create temporary storage #
            mkdir -p $SRM_TMP_NAME

        elif [ "$1" == "delete" ]; then

            # Check temporary storage #
            if [ -d $SRM_TMP_NAME ]; then

                # Delete temporary storage #
                rm -rf $SRM_TMP_NAME

            fi

        fi

    }

# Calibration data access
#
# This function allows to query calibration data through the standard storage
# structure. It expects the device MAC address and the key of the desired value
# and returns it when the key is found in the calibration data. An empty string
# is return otherwise.

    function srm_askc() {

        # Reads and returns value of key #
        echo $(grep "$2" $SRM_MNT_BASE/camera/$1/fastcal/calibration.key | cut -d'=' -f2)

    }

# Module kernel specific function (elphel-plugin@elphel)
#
# This function implements the Elphel plugin call to perform refinement of the
# data considered by the module. It starts by editing the configuration file in
# order to specify the correct path before to call the plugin. It ends its task
# by renaming the output files and by merging the tiles that are provided in two
# parts by the plugin.

    function srm_elphel_plugin() {

        # Defines XML keys #
        SRM_XML_TAG01="CORRECTION_PARAMETERS.smoothKernelDirectory"
        SRM_XML_TAG02="CORRECTION_PARAMETERS.sharpKernelDirectory"
        SRM_XML_TAG03="CORRECTION_PARAMETERS.sensorDirectory"
        SRM_XML_TAG04="CORRECTION_PARAMETERS.equirectangularDirectory"
        SRM_XML_TAG05="CORRECTION_PARAMETERS.resultsDirectory"
        SRM_XML_TAG06="CORRECTION_PARAMETERS.sourcePath"
        SRM_XML_TAG07="CORRECTION_PARAMETERS.sourcePaths"

        # Compose edited XML configuration file path #
        SRM_XML_PATH=$SRM_TMP_NAME/elphel-correction.xml

        # Creating edited XML configuration file #
        > $SRM_XML_PATH; while read SRM_LINE; do

            # Detects specific keys #
            if [[ $SRM_LINE == *$SRM_XML_TAG01* ]]; then

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG01\">$SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/calibration/kernels/smooth</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *$SRM_XML_TAG02* ]]; then

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG02\">$SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/calibration/kernels/sharp</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *$SRM_XML_TAG03* ]]; then

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG03\">$SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/calibration/sensors</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *$SRM_XML_TAG04* ]]; then

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG04\">$SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/calibration/maps</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *$SRM_XML_TAG05* ]]; then

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG05\">$SRM_TMP_NAME</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *"THREADS_MAX"* ]]; then

                # Export XML entry #
                echo "<entry key=\"THREADS_MAX\">$SRM_PLL_CONF</entry>" >> $SRM_XML_PATH

            elif [[ $SRM_LINE == *"</properties>"* ]]; then

                # Inserting source file in configuration #
                SRM_LS_NUMS=0; for SRM_LS_FILE in $SRM_IO_IPOS/*.jp4; do

                    # Export XML entry #
                    echo "<entry key=\"${SRM_XML_TAG06}${SRM_LS_NUMS}\">$SRM_LS_FILE</entry>" >> $SRM_XML_PATH

                    # Update index #
                    SRM_LS_NUMS=$(( $SRM_LS_NUMS + 1 ))

                done

                # Export XML entry #
                echo "<entry key=\"$SRM_XML_TAG07\">$SRM_LS_NUMS</entry>" >> $SRM_XML_PATH

                # Export XML entry #
                echo $SRM_LINE >> $SRM_XML_PATH

            elif [[ ! $SRM_LINE == *$SRM_XML_TAG06* ]]; then

                # Export XML entry #
                echo $SRM_LINE >> $SRM_XML_PATH

            fi

        done < $SRM_MNT_BASE/camera/${SRM_IO_PART[2]}/imagej-elphel/prefs.xml

        # Elphel plugin #
        ImageJ-linux64 --headless --mem 7150m --run Eyesis_Correction prefs=$SRM_XML_PATH &> /dev/null

        # Parsing result image #
        for SRM_EXE_FILE in $SRM_TMP_NAME/*.tiff; do

            # Extract file basename #
            SRM_EXE_BASE=$(basename $SRM_EXE_FILE)

            # Decompose basename #
            SRM_EXE_ELEM=(${SRM_EXE_BASE//-/ })

            # Recompose basename #
            SRM_EXE_NAME=${SRM_EXE_ELEM[0]}_${SRM_EXE_ELEM[1]}

            # Detect splitted tiles #
            if [[ $SRM_EXE_BASE == *"-LEFT"* ]]; then

                # Add suffix to recomposed basename #
                SRM_EXE_NAME=${SRM_EXE_NAME}_L

            elif [[ $SRM_EXE_BASE == *"-RIGHT"* ]]; then

                # Add suffix to recomposed basename #
                SRM_EXE_NAME=${SRM_EXE_NAME}_R

            fi

            # Adding extension to recomposed basename #
            SRM_EXE_NAME=$SRM_TMP_NAME/$SRM_EXE_NAME.tiff

            # Rename result file #
            mv $SRM_EXE_FILE $SRM_EXE_NAME

        done

        # Parsing result images #
        for SRM_EXE_FILE in $SRM_TMP_NAME/*.tiff; do

            # Extract file basename #
            SRM_EXE_BASE=$(basename $SRM_EXE_FILE)

            # Decompose basename #
            SRM_EXE_ELEM=(${SRM_EXE_BASE//_/ })            

            # Search for split images #
            if [[ $SRM_EXE_BASE == *"_L"* ]]; then

                # Search for second image part #
                if [ -f $SRM_TMP_NAME/${SRM_EXE_ELEM[0]}_${SRM_EXE_ELEM[1]}_${SRM_EXE_ELEM[2]}_R.tiff ]; then

                    # Rebuild whole image #
                    convert +append $SRM_TMP_NAME/${SRM_EXE_ELEM[0]}_${SRM_EXE_ELEM[1]}_${SRM_EXE_ELEM[2]}_L.tiff \
                                    $SRM_TMP_NAME/${SRM_EXE_ELEM[0]}_${SRM_EXE_ELEM[1]}_${SRM_EXE_ELEM[2]}_R.tiff \
                                    $SRM_TMP_NAME/${SRM_EXE_ELEM[0]}_${SRM_EXE_ELEM[1]}_${SRM_EXE_ELEM[2]}.tiff &> /dev/null

                fi

            fi

        done

        # Inject results in storage structure #
        rsync $SRM_TMP_NAME/*.tiff $SRM_IO_OPOS/

    }

# Module kernel function
#
# The kernel function is responsible of analyzing instructions provided by the
# module main script and to trigger selected poses processing. This function is
# broadcasted to the computers and threads according to the provided network
# topology.

    # Arguments and parameters #
    srm_arg $@

    # Decompose IO buffer #
    SRM_IO_PART=(${SRM_IO_PATH//,/ })

    # Compose pose identification #
    SRM_IO_POSE=${SRM_IO_PART[5]}

    # Compose pose source and destination directories #
    SRM_IO_IPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[0]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}
    SRM_IO_OPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[1]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}

    # Check source element #
    if [ ! -d $SRM_IO_IPOS ]; then

        # Display message and update exit code #
        srm_echo "SRM Kernel : Error, invalid module kernel io specification"; SRM_SIG_EXIT=1

    else

        # Display message #
        srm_echo "    element ${SRM_IO_PART[5]}"

        # Check module mode #
        if [ "$SRM_KER_MODE" == "elphel-plugin" ]; then

            # Check device constructor #
            if [ "$(srm_askc ${SRM_IO_PART[2]} "constructor")" == "elphel" ]; then

                # Check pose state #
                if ( [ -d $SRM_IO_OPOS ] && [ "$SRM_KER_FORC" == "true" ] ) || [ ! -d $SRM_IO_OPOS ]; then

                    # Temporary storage #
                    srm_tmpfs create

                    # Remove previous data #
                    if [ -d $SRM_IO_OPOS ]; then rm -rf $SRM_IO_OPOS; fi

                    # Create destination pose directory #
                    mkdir -p $SRM_IO_OPOS

                    # Refinement process #
                    srm_elphel_plugin

                    # Temporary storage #
                    srm_tmpfs delete

                fi

            else

                # Display message and update exit code #
                srm_echo "SRM Kernel : Error, unknown device constructor"; SRM_SIG_EXIT=1

            fi

        else

            # Display message and update exit code #
            srm_echo "SRM Kernel : Error, unknown module mode"; SRM_SIG_EXIT=1

        fi

    fi

    # Exit code #
    exit $SRM_SIG_EXIT
