#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

    # Storage variables #
    SRM_MNT_BASE="/data/"

    # Execution variables #
    SRM_KER_FORC="false"
    SRM_KER_MODE="unknown"

    # Temporary storage variables #
    SRM_TMP_NAME=""

    # Communication variables #
    SRM_IO_PATH=""
    SRM_IO_IPOS=""
    SRM_IO_OPOS=""

    # Parallel variables #
    SRM_PLL_CONF="1"

    # Signal variables #
    SRM_SIG_EXIT=0

# Argument and parameter
#
# This function reads the module script arguments and parameters using the
# assuption that every argument always comes with a unique parameter.

    function srm_arg() {

        # Arguments and parameters #
        while [[ $# > 0 ]]; do

            # Read token and update head #
            srm_arg="$1"; shift
            srm_prm="$1"; shift

            # Switch on arguments #
            case $srm_arg in

                --mount-point)
                    SRM_MNT_BASE="$srm_prm"
                ;;
                --local-thread)
                    SRM_PLL_CONF="$srm_prm"
                ;;
                --force)
                    SRM_KER_FORC="$srm_prm"
                ;;
                --io)
                    SRM_IO_PATH="$srm_prm"
                ;;

            esac

        done

    }

# Message display
#
# The following function simply displays the string provdided as parameter using
# the standard error as output.

    function srm_echo() {

        # Display message #
        >&2 echo "$1"
        
    }

# Timestamps hashing
#
# This function returns the hashed (truncated) timestamps value for any given
# timestamp according to the storage structure standards. It corresponds to a
# simple division by ten.

    function srm_tshash() {

        # Retrieve unix timestamps #
        SRM_TS_UNIX=(${1//_/ })

        # Returns hashed timestamps #
        echo $(( ${SRM_TS_UNIX[0]} / 100 ))

    }

# Temporary file system
#
# This function creates a temporary storage (tmpfs) in case module requires
# fast-access storage. It also allows to delete the temporary storage as the
# module ends its task.

    function srm_tmpfs() {

        # Create temporary storage path #
        SRM_TMP_NAME=/run/shm/$(echo "$SRM_IO_PATH" | sha256sum | cut -c 1-32)

        # Temporary storage management #
        if [ "$1" == "create" ]; then

            # Create temporary storage #
            mkdir -p $SRM_TMP_NAME

        elif [ "$1" == "delete" ]; then

            # Check temporary storage #
            if [ -d $SRM_TMP_NAME ]; then

                # Delete temporary storage #
                rm -rf $SRM_TMP_NAME

            fi

        fi

    }

# Calibration data access
#
# This function allows to query calibration data through the standard storage
# structure. It expects the device MAC address and the key of the desired value
# and returns it when the key is found in the calibration data. An empty string
# is return otherwise.

    function srm_askc() {

        # Reads and returns value of key #
        echo $(grep "$2" $SRM_MNT_BASE/camera/$1/fastcal/calibration.key | cut -d'=' -f2)

    }

# Module kernel specific function
#
# This function is used to inject validated poses coming from Elphel digitising
# devices in the standard storage structure. It simply creates soft links to the
# validated poses in the raw data storage structure.

    function srm_inject_elphel() {

        # Initialize device module parser #
        SRM_IDX_MODE=1

        # Parses device modules #
        while [ -f ${SRM_IO_IPOS}_${SRM_IDX_MODE}.jp4 ]; do

            # Create soft link #
            ln -sf ${SRM_IO_IPOS}_${SRM_IDX_MODE}.jp4 $SRM_IO_OPOS/

            # Update index #
            SRM_IDX_MODE=$(( $SRM_IDX_MODE + 1 ))

        done        

    }

# Module kernel function
#
# The kernel function is responsible of analyzing instructions provided by the
# module main script and to trigger selected poses processing. This function is
# broadcasted to the computers and threads according to the provided network
# topology.

    # Arguments and parameters #
    srm_arg $@

    # Decompose IO buffer #
    SRM_IO_PART=(${SRM_IO_PATH//,/ })

    # Compose pose identification #
    SRM_IO_POSE=${SRM_IO_PART[5]}

    # Compose specific source #
    SRM_IO_IPOS=$SRM_MNT_BASE/rawdata/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/raw/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}

    # Compose destination #
    SRM_IO_OPOS=$SRM_MNT_BASE/pose/${SRM_IO_PART[1]}/data/${SRM_IO_PART[2]}/master/${SRM_IO_PART[3]}/segment/${SRM_IO_PART[4]}/pose/$(srm_tshash ${SRM_IO_PART[5]})/${SRM_IO_PART[5]}

    # Check source element #
    if [ ! -f ${SRM_IO_IPOS}_1.jp4 ]; then

        # Display message and update exit code #
        srm_echo "SRM Kernel : Error, invalid module kernel io specification"; SRM_SIG_EXIT=1

    else

        # Display message #
        srm_echo "    rawdata ${SRM_IO_PART[5]} of camera ${SRM_IO_PART[2]}"

        # Check device constructor #
        if [ "$(srm_askc ${SRM_IO_PART[2]} "constructor")" == "elphel" ]; then

            # Check pose state #
            if ( [ -d $SRM_IO_OPOS ] && [ "$SRM_KER_FORC" == "true" ] ) || [ ! -d $SRM_IO_OPOS ]; then

                # Remove previous data #
                if [ -d $SRM_IO_OPOS ]; then rm -rf $SRM_IO_OPOS; fi

                # Create destination pose directory #
                mkdir -p $SRM_IO_OPOS

                # Refinement process #
                srm_inject_elphel

            fi

        else

            # Display message and update exit code #
            srm_echo "SRM Kernel : Error, unknown device constructor"; SRM_SIG_EXIT=1

        fi

    fi

    # Exit code #
    exit $SRM_SIG_EXIT

