#!/bin/bash
# srm-kernel - Standard refinement modules
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

    # Module io classification variables #
    SRM_IO_INPUT="eyesis4pi-raw"
    SRM_IO_OUTPUT="template-module"

    # Command variables #
    SRM_CMD_NORM="$(basename $0)"
    SRM_CMD_HASH="$(basename $0)"

    # Storage structure variables #
    SRM_MNT_BASE="/data/"    

    # Module execution variables #
    SRM_MOD_EXEC="default"
    SRM_MOD_MMSR=""
    SRM_MOD_NODE=""

    # Module statistic variables #
    SRM_STA_POSE=0
    SRM_STA_PROC=0

    # Temporary storage variables #
    SRM_TMP_NAME=""

    # Module execution variables #
    SRM_EID_EXIT=0

# Argument and parameter
#
# This function reads the module script arguments and parameters using the
# assuption that every argument always comes with a unique parameter. Moreover
# this function creates and normalized and simplified representation of the
# script command.

    function srm_arg() {

        # Parses the arguments and parameters #
        while [[ $# > 0 ]]; do

            # Push token and update head #
            srm_arg="$1"; shift
            srm_prm="$1"; shift

            # Switch on arguments #
            case $srm_arg in

                --mount-point)
                    SRM_MNT_BASE="$srm_prm"
                ;;

                --address)
                    SRM_MOD_MMSR="$SRM_MOD_MMSR $srm_prm"
                ;;

                --display)
                    SRM_MOD_EXEC="$srm_prm"
                ;;

                -n)
                    SRM_MOD_NODE="$srm_prm"
                ;;

            esac

            # Compose normalized command #
            SRM_CMD_NORM="$SRM_CMD_NORM $srm_arg $srm_prm"

            # Filter arguments and parameters #
            if [ "${srm_arg:1:1}" != "-" ]; then 

                # Compose simplified command #
                SRM_CMD_HASH="$SRM_CMD_HASH $srm_arg $srm_prm"; 

            fi

        done

    }

# Message display
#
# The following function simply displays the string provdided as parameter using
# the standard error output.

    function srm_echo() {

        # Display message #
        >&2 echo "$1"
        
    }

# Module hash
#
# This function computes the hash used to identify the module processing results
# in the storage structure. An SHA256 sum is considered as hash algorithm and
# only the 16 first hexadecimal digits of the hash are kept.

    function srm_hash() {

        # Compute SHA256 sum #
        SRM_SHA_S256=$(echo "$1" | sha256sum)

        # Return truncated SHA256 sum #
        echo "${SRM_SHA_S256:0:16}"

    }

# Temporary file system
#
# This function creates a temporary storage (tmpfs) in case module requires
# fast-access storage. It also allows to delete the temporary storage as the
# module ends its task.

    function srm_tmpfs() {

        # Create temporary storage name #
        SRM_TMP_NAME=$(echo "$SRM_CMD_NORM" | sha256sum)
        SRM_TMP_NAME=/dev/shm/${SRM_TMP_NAME:0:32}

        # Temporary storage management #
        if [ "$1" == "create" ]; then

            # Create temporary storage #
            mkdir -p $SRM_TMP_NAME

        elif [ "$1" == "delete" ]; then

            # Delete temporary storage #
            rm -rf $SRM_TMP_NAME

        fi

    }

# Timestamps simple hashing
#
# This function returns the hashed (truncated) timestamps value for any given
# timestamp according to the storage structure standards. It corresponds to a
# simple division by ten.

    function srm_tshash() {

        # Retrieve unix timestamp - if composed #
        SRM_TS_UNIX=(${1//_/ })

        # Returns hashed timestmap #
        echo $(( ${SRM_TS_UNIX[0]} / 100 ))

    }

# Timestamps selection
#
# This function detects if a given timestamps, provided by the considered pose,
# is or not in the range of a mmsr address. In order to perform the check, the
# function waits the pose timestamps and the two downer and upper timestamps of
# the mmsr address.

    function srm_selected() {

        # Decompose pose timestamps #
        SRM_TS_PART=(${1//_/ })
        SRM_TS_UNIX=${SRM_TS_PART[0]}
        SRM_TS_USEC=${SRM_TS_PART[1]}

        # Decompose mmsr downer and upper timestamps #
        SRM_ML_PART=(${2//_/ })
        SRM_MH_PART=(${3//_/ })
        SRM_ML_UNIX=${SRM_ML_PART[0]}
        SRM_MH_UNIX=${SRM_MH_PART[0]}
        SRM_ML_USEC=${SRM_ML_PART[1]}
        SRM_MH_USEC=${SRM_MH_PART[1]}

        # Initialize result #
        SRM_RETURN=1

        # Check downer boundary #
        if (( $SRM_TS_UNIX < $SRM_ML_UNIX )); then

            # Return result #
            SRM_RETURN=0

        fi

        # Check downer boundary #
        if (( $SRM_TS_UNIX == $SRM_ML_UNIX )); then

            # Check decimale boundary #
            if (( $SRM_TS_USEC < $SRM_ML_USEC )); then

                # Return result #
                SRM_RETURN=0

            fi

        fi

        # Check upper boundary #
        if (( $SRM_TS_UNIX > $SRM_MH_UNIX )); then

            # Return result #
            SRM_RETURN=0

        fi

        # Check upper boundary #
        if (( $SRM_TS_UNIX == $SRM_MH_UNIX )); then

            # Check decimale boundary #
            if (( $SRM_TS_USEC > $SRM_ML_USEC )); then

                # Return result #
                SRM_RETURN=0

            fi

        fi

        # Return result #
        echo $SRM_RETURN

    }

# Module main function
#
# The following instructions are responsible of performing the tasks the module
# is supposed to do. This main function is also responsible of the management of
# errors and the exit message to the system.

    # Argument and parameter #
    srm_arg $@

    # Module hash #
    SRM_MOD_HASH=$(srm_hash "$SRM_CMD_HASH")

    # Module execution switch #
    if [ "$SRM_MOD_EXEC" == "default" ]; then

        # Check source node availability #
        if [ ! -d $SRM_MNT_BASE/pose/$SRM_MOD_NODE/ ]; then

            # Display message #
            srm_echo "SRM Kernel : Error, unknown source node"; SRM_EID_EXIT=1

        else

            # Check source data classification #
            if [ ! -e $SRM_MNT_BASE/pose/$SRM_MOD_NODE/info/$SRM_IO_INPUT ]; then

                # Display message #
                srm_echo "SRM Kernel : Error, invalid source classification"; SRM_EID_EXIT=1

            else

                # Temporary storage #
                srm_tmpfs create

                # Display module summary #
                srm_echo "SRM Kernel : $(basename $0)"
                srm_echo "    cmd : $SRM_CMD_NORM"
                srm_echo "    sha : $SRM_CMD_HASH"
                srm_echo "    has : $SRM_MOD_HASH"
                srm_echo "    src : $SRM_MOD_NODE"

                # Parse mmsr addresses #
                for SRM_EXE_MSSR in $SRM_MOD_MMSR; do

                    # Display mmsr address #
                    srm_echo "SRM Kernel : address $SRM_EXE_MSSR"

                    # Reset module statistic #
                    SRM_STA_POSE=0
                    SRM_STA_PROC=0

                    # Decompose mmsr address #
                    SRM_ADD_MAIN=(${SRM_EXE_MSSR//// })
                    SRM_ADD_POSE=(${SRM_ADD_MAIN[3]//-/ })

                    # Display decomposed mmsr address #
                    srm_echo "    mac : ${SRM_ADD_MAIN[0]}"
                    srm_echo "    mas : ${SRM_ADD_MAIN[1]}"
                    srm_echo "    seg : ${SRM_ADD_MAIN[2]}"
                    srm_echo "    ran : ${SRM_ADD_POSE[0]} to ${SRM_ADD_POSE[1]}"

                    # Parse mmrs address poses #
                    for SRM_EXE_POSE in $SRM_MNT_BASE/pose/$SRM_MOD_NODE/data/${SRM_ADD_MAIN[0]}/master/${SRM_ADD_MAIN[1]}/segment/${SRM_ADD_MAIN[2]}/pose/$(srm_tshash ${SRM_ADD_MAIN[2]})/*; do

                        # Parse only directories #
                        if [ -d $SRM_EXE_POSE ]; then

                            # Update module statistic #
                            SRM_STA_POSE=$(( $SRM_STA_POSE + 1 ))

                            # Selection on mmsr address #
                            if (( $(srm_selected $(basename $SRM_EXE_POSE) ${SRM_ADD_POSE[0]} ${SRM_ADD_POSE[1]}) == 1 )); then

                                # Update module statistic #
                                SRM_STA_PROC=$(( $SRM_STA_PROC + 1 ))

                            fi

                        fi

                    done

                    # Display module statistic #
                    srm_echo "    res : $SRM_STA_PROC/$SRM_STA_POSE"

                done

                # Temporary storage #
                srm_tmpfs delete

            fi

        fi

    elif [ "$SRM_MOD_EXEC" == "list-nodes" ]; then

        # Display available input nodes #
        for SRM_NOD_INPUT in $SRM_MNT_BASE/pose/*; do

            # Detects directories #
            if [ -e $SRM_NOD_INPUT/info/$SRM_IO_INPUT ]; then

                # Display source node #
                srm_echo "$(basename $SRM_NOD_INPUT)"

            fi

        done

    elif [ "$SRM_MOD_EXEC" == "input-classification" ]; then

        # Display module classification #
        srm_echo "$SRM_IO_INPUT"

    elif [ "$SRM_MOD_EXEC" == "output-classification" ]; then

        # Display module classification #
        srm_echo "$SRM_IO_OUTPUT"

    else

        # Display message #
        srm_echo "SRM - Kernel : Error, invalid module mode"; SRM_EID_EXIT=1

    fi

    # Exit code #
    exit $SRM_EID_EXIT

